# Generated by Django 4.1.6 on 2023-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='hi', max_length=75),
            preserve_default=False,
        ),
    ]
