# Generated by Django 4.1.7 on 2023-02-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
