# Generated by Django 4.1.7 on 2023-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0003_remove_comment_post_delete_user_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
