# Generated by Django 4.1.7 on 2023-02-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0004_alter_comment_user_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='foodies.post'),
        ),
    ]
